version: '3'
services:

  rust_alpine:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: ${PROJECT_NAME}
    hostname: rustup.${PROJECT_NAME}.local
    domainname: ${PROJECT_NAME}.local
    user: "${UID}:${GID}"
    tty: true
    volumes:
      - ${FOLDER_PATH}:/rust
    ports:
      - ${PORT:-8000}:8000
    networks:
      devEnvLocal:
        aliases:
          - rust.devEnv.local

networks:
  devEnvLocal:
    driver: bridge
    name: ${PROJECT_NAME}_devEnvLocal
